"""
routes/recommendations.py
-------------------------
Route: POST /recommend
Returns crop recommendations for given farm conditions.
"""

from fastapi import APIRouter
from models.recommendation import RecommendationInput, RecommendationResponse
from services.recommendation_service import get_crop_recommendations

router = APIRouter()


@router.post(
    "/recommend",
    response_model=RecommendationResponse,
    summary="Get Crop Recommendations",
    description=(
        "Submit farm details to receive a ranked list of suitable crops. "
        "Recommendations are generated by a rule-based prototype engine — "
        "NOT a trained AI/ML model."
    ),
)
def recommend_crops(farm: RecommendationInput) -> RecommendationResponse:
    """
    Return ranked crop recommendations for the given farm conditions.

    The route delegates all logic to recommendation_service.
    To integrate a future ML model, replace the service implementation —
    this route does not need to change.
    """
    recommendations = get_crop_recommendations(farm)
    return RecommendationResponse(
        location=farm.location,
        season=farm.season,
        soil_type=farm.soil_type,
        recommendations=recommendations,
    )
