"""
models/recommendation.py
-------------------------
Pydantic models for crop recommendation input and response.
"""

from typing import List, Optional
from pydantic import BaseModel, Field


class RecommendationInput(BaseModel):
    """
    Input for crop recommendation.
    Mirrors FarmInput — kept separate so the recommendation endpoint
    can evolve independently of farm registration.
    """

    location: str = Field(..., description="Location name")
    area: float = Field(..., gt=0, description="Farm area in acres")
    soil_type: str = Field(..., description="Soil type, e.g. 'red', 'black', 'loamy'")
    soil_ph: float = Field(..., ge=0, le=14, description="Soil pH (0–14)")
    water_availability: str = Field(..., description="'low', 'medium', or 'high'")
    budget: float = Field(..., ge=0, description="Budget in INR")
    season: str = Field(..., description="'kharif' or 'rabi'")
    previous_crop: Optional[str] = Field(None, description="Previous crop (optional)")


class CropRecommendation(BaseModel):
    """A single recommended crop with reasoning and estimates."""

    crop: str
    suitability_score: int = Field(..., description="Score out of 100")
    reason: str = Field(..., description="Human-readable explanation of why this crop was recommended")
    estimated_yield_per_acre: float = Field(..., description="Estimated yield in quintals per acre (prototype)")
    estimated_cost_inr: float = Field(..., description="Estimated total cost in INR (prototype)")
    estimated_revenue_inr: float = Field(..., description="Estimated total revenue in INR (prototype)")
    estimated_profit_inr: float = Field(..., description="Estimated profit in INR (prototype)")
    risk_level: str = Field(..., description="'Low', 'Medium', or 'High'")


class RecommendationResponse(BaseModel):
    """Full recommendation response containing ranked crop suggestions."""

    location: str
    season: str
    soil_type: str
    recommendations: List[CropRecommendation]
    disclaimer: str = (
        "Recommendations are generated by a rule-based prototype engine. "
        "All yield, cost, and profit figures are estimates for demo purposes only. "
        "This is NOT a trained AI/ML model."
    )
